appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.2.3
appReplicas: 0
containerPort: 3550
containerEnvVars: 
- name: PORT
  value: "3550"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1" 
- name: DISABLE_DEBUGGER
  value: "1"

service:
  port: 3550
