appName: shippingservice 
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.2.3
appReplicas: 0
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"

service:
  port: 50051
